baseURL = 'https://blog.astrozen.me/'
title = 'ASTROZEN BLOG'
copyright = "© 2023-{year} [ASTROZEN BLOG](https://blog.astrozen.me) Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

theme = 'PaperMod'

languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true

[permalinks]
    posts = '/:year/:month/:title/'

[outputs]
    home = ['HTML', 'RSS', 'JSON']

[taxonomies]
    category = 'categories'
    tag = 'tags'
    series = 'series'

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
            [markup.goldmark.extensions.passthrough.delimiters]
                block = [['\[', '\]'], ['$$', '$$']]
                inline = [['\(', '\)']]

    [markup.highlight]
        # anchorLineNos = true
        codeFences = true
        guessSyntax = true
        lineNos = true
        noClasses = false

[params]
    #PaperMod theme
    env = 'production'
    author = 'Astrozen'
    description = "Astrozen's blog"
    keywords = ['blog', 'page', 'personal', 'developer']
    ShowReadingTime = false
    ShowWordCount = false
    disableSpecial1stPost = true
    hideSummary = true
    ShowToc = true
    tocopen = false
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    comments = true
    hideFooter = true # use my own extend_footer.html

    homeInfoParams.Title = 'Hi there 👋'
    homeInfoParams.Content = 'Welcome to my blog'

    assetsdisableHLJS = true

[[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/wirano'
[[params.socialIcons]]
    name = 'email'
    url = 'mailto:i@wirano.me'
[[params.socialIcons]]
    name = 'rss'
    url = 'index.xml'
[[params.socialIcons]]
    name = 'key'
    url = 'https://github.com/wirano.gpg'

[[menu.main]]
    name = 'Home'
    url = '/'
    weight = -10
[[menu.main]]
    name = 'Series'
    url = '/series/'
    weight = 10
[[menu.main]]
    name = 'Tags'
    url = '/tags/'
    weight = 20
[[menu.main]]
    name = 'Links'
    url = '/links/'
    weight = 30
[[menu.main]]
    name = 'Archive'
    url = '/archives/'
    weight = 40
[[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 50
[[menu.main]]
    name = 'Search'
    url = '/search/'
    weight = 60

